NitecoProgrammingTest/Pages/User/UserMainPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NitecoProgrammingTest.Models;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NitecoProgrammingTest.Pages.User
{
    public class UserMainPageModel : PageModel
    {
        private readonly AppDbContext _context;
        private readonly ILogger<UserMainPageModel> _logger;

        public UserMainPageModel(AppDbContext context, ILogger<UserMainPageModel> logger)
        {
            _context = context;
            _logger = logger;
        }
        [BindProperty]
        public Order Order { get; set; }

        [BindProperty]
        public string ErrorMessage { get; set; }
        public List<Order> AllOrderList { get; set; }
        public List<SelectListItem> ProductNameListItem { get; set; }

        public List<SelectListItem> CustomerNameListItem { get; set; }
        public void OnGet()
        {
            AllOrderList = _context.Orders
                                   .Include(o => o.Customer)
                                   .Include(o => o.Product)
                                   .ThenInclude(o => o.Category)
                                   .ToList();
            ProductNameListItem = _context.Products.Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.Name

            }).ToList();

            CustomerNameListItem = _context.Customers.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name

            }).ToList();

        }
        public List<Order> GetAllOrders(string categoryName = null)
        {
            if (categoryName != null)
            {
                return _context.Orders
                            .Include(o => o.Customer)
                            .Include(o => o.Product)
                            .ThenInclude(o => o.Category)
                            .Where(o => o.Product.Category.Name.ToLower().Contains(categoryName.ToLower()))
                            .ToList();
            }
            else
            {
                return _context.Orders
                            .Include(o => o.Customer)
                            .Include(o => o.Product)
                            .ThenInclude(o => o.Category)
                            .ToList();
            }
        }
        public async Task<IActionResult> OnPostAsync()
        {
            AllOrderList = GetAllOrders();
            ProductNameListItem = _context.Products.Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.Name

            }).ToList();

            CustomerNameListItem = _context.Customers.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name

            }).ToList();


            if (ModelState.IsValid)
            {

                var product = _context.Products.Find(Order.ProductId);
                if (Order.Amount <= product.Quantity)
                {
                    try
                    {
                        //Order.Id = _context.Orders.Count();
                        await _context.Orders.AddAsync(Order);
                        var result = await _context.SaveChangesAsync();
                        return RedirectToPage("./UserMainPage");
                    }
                    catch (DbUpdateException ex)
                    {
                        _logger.LogError(ex.Message);
                        ErrorMessage = ex.Message;
                    }
                }
                else
                {
                    ErrorMessage = "The amount of the order is greater than the quantity of the product";
                }
            }

            return Page();
        }

        public async Task<IActionResult> OnPostFindOrdersByCategoryAsync()
        {
            var categoryName = Request.Form["categoryName"].ToString();
            AllOrderList = GetAllOrders(categoryName);
            ProductNameListItem = _context.Products.Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.Name

            }).ToList();

            CustomerNameListItem = _context.Customers.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name

            }).ToList();
            //Debug.WriteLine("here");
            return Page();
        }
    }
}

NitecoProgrammingTest/Pages/User/UserMainPage.cshtml
@page
@model NitecoProgrammingTest.Pages.User.UserMainPageModel
@{
}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>

<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

<h2 class="text-danger">@Model.ErrorMessage</h2>

<form method="post" asp-page-handler="FindOrdersByCategory">
    <fieldset>
        <div class="row">
            <div class="col-lg-4">
                <label>Enter category to search</label>
                
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <input type="text" name="categoryName" class="form-control" />

            </div>
            <div class="col-lg-1">
                <input type="submit" value="search" class="btn btn-primary"/>
            </div>
        </div>
</fieldset>
</form>

<table id="dataTable" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr style="background:#337ab7; color:white;">
            <th>
                Product Name
            </th>
            <th>
                Category Name
            </th>
            <th>
                Customer Name
            </th>
            <th>
                Order Date
            </th>
            <th>
                Amount
            </th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model.AllOrderList)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.Name)
                </td>
                <td>
                    @Html.Raw(item.OrderDate.ToShortDateString())
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
            </tr>

        }
    </tbody>
</table>

<div class="text-right">
    <input class="btn-primary btn btn-sm btn-info" type="button" id="createButton" data-toggle="modal" data-target="#CreateOrderModal" value="Create new order" />
</div>
<div class="modal fade" id="CreateOrderModal" tabindex="-1" role="dialog" aria-labelledby="CreateOrderModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="FinishModalLabel">Create New Order</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-3">
                                <label>Order name</label>
                            </div>
                            <div class="col-lg-7">
                                <input class="form-control"  id="orderName" />
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-3">
                                <label>Product</label>
                            </div>
                            <div class="col-lg-7">
                                <select asp-items="Model.ProductNameListItem" asp-for="Order.ProductId"   style="width:100% ">
                                    <option  value=""> </option>
                                </select>
                                <span asp-validation-for="Order.ProductId" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-3">
                                <label>Customer</label>
                            </div>

                            <div class="col-lg-7">
                                <select asp-items="Model.CustomerNameListItem" asp-for="Order.CustomerId" style="width:100%">
                                    <option value=""> </option>
                                </select>
                                <span asp-validation-for="Order.CustomerId" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-3">
                                <label>Order Date</label>
                            </div>
                            <div class="col-lg-7">
                                <input id="datepicker" style="width:80%" asp-for="Order.OrderDate" type="datetime" />
                                <span asp-validation-for="Order.OrderDate" class="text-danger"></span>
                            </div>
                            <!-- <input class="form-control" id="formTitle" /> -->
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-lg-3">
                                <label>Amount</label>
                            </div>
                            <div class="col-lg-7">
                                <!-- <input class="form-control" id="formTitle" /> -->
                                <input class="form-control" id="amount" asp-for="Order.Amount"/>
                                <span asp-validation-for="Order.Amount" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="text-right">
                        <input class="btn-primary btn btn-sm btn-info" type="submit" value="Create Order" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script src="~/js/userMainPage.js"></script>